server:
  port: 8072

spring:
  application.name: gateway-server
  cloud:
    gateway:
      routes:
        - id: truck
          uri: http://gotruck-server:807/truck
          predicates:
            Path=/truck/**
          filters:
            TokenRelay=

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
    registerWithEureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: truck_go
            client-secret: kZVlXsCxWhNCMpIKjeMDYEfc5SDXOoKL
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "http://backend-gateway-client:8083/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keylcloak:8080/auth/realms/truckgo

management:
  endpoints:
    web:
      exposure:
        include: "*"
