version: "3.9"

services:

  postgres:
    image: postgres:11

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres


  configserver:
    image: lucasit/configservice:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: lucasit/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    #    depends_on:
    #      #      database:
    #      #        condition: service_healthy
    #      configserver:
    #        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"

  apigateway:
    image: lucasit/service-gateway:0.0.1-SNAPSHOT
    ports:
      - 8072:8072
    networks:
      backend:
        aliases:
          - "apigateway"


  gotruckservice:
    image: lucasit/gotruckservice:0.0.1-SNAPSHOT
    ports:
      - "8073:8073"
    #    depends_on:
    #      #      database:
    #      #        condition: service_healthy
    #      configserver:
    #        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"

networks:
  backend:
    driver: bridge
volumes:
  data-volume3: